# Generated by Django 4.2.5 on 2023-09-25 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('price_unit', models.CharField(max_length=50)),
                ('price_type', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
                ('property_category', models.CharField(max_length=50)),
                ('post_type', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=500)),
                ('lat', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(max_length=5000)),
                ('hide_contact', models.CharField(choices=[('1', 'No'), ('2', 'Yes')], default=1, max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.address')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('size_unit', models.CharField(max_length=20)),
                ('lot_size', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('roofing', models.CharField(max_length=100)),
                ('structure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to='pvideo/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertydetails'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pimages/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
